lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Path to your private key
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # Path to your public key
    pass_phrase: 'lmslms'                           # Your private key passphrase
    token_ttl: 3600                                         # Token validity in seconds (1 hour)
