security:
    # Password hashers configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Developer tools
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # JWT login firewall
        login:
            pattern: ^/authentication_token
            stateless: true
            json_login:
                check_path: /authentication_token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # API firewall
        api:
            pattern: ^/api
            stateless: true
            jwt: ~ # Enables the JWT listener
            provider: app_user_provider

    # Access controls
    access_control:
        - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allow login access
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
